#!/bin/sh
## EPITECH PROJECT, 2017
## test
## File description:
## test
##

#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so xflock4
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so htop
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so google-chrome-stable
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so firefox
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so vi
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so ls -lA
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so clear
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so reset
#LD_PRELOAD=./libmy_malloc.so valgrind --soname-synonyms=somalloc=libmy_malloc.so bc
